/* Lab 2 Model Practical — real class-model photos (Gabe's, shot in lab 2026-07-18).
   Recognition-first station deck: show a photo → "what model / structure / view is this?" →
   reveal + self-grade. `answer` = the identification; `hint` = key structures visible (teaching on
   reveal); `system` groups stations for weak-station review; `verify:true` = my ID is best-guess,
   confirm against the lab key. Numbered-label answer keys are a later add (needs the worksheet). */
const LAB2_MODELS = [
  { id: "lm01", file: "lab2models/lab2_model_01.jpg", system: "Torso / viscera",
    answer: "Torso model — head, neck & thorax (anterior)",
    hint: "Sagittal skull + brain, neck muscles, internal jugular (blue) & common carotid (red), thyroid gland, lungs." },
  { id: "lm02", file: "lab2models/lab2_model_02.jpg", system: "Digestive",
    answer: "Abdominal viscera — pancreas, duodenum, stomach, small intestine",
    hint: "Pancreas (tan, with duodenal C-loop), stomach (grey), coils of small intestine, spleen." },
  { id: "lm03", file: "lab2models/lab2_model_03.jpg", system: "Digestive",
    answer: "Liver — visceral (inferior) surface, with gallbladder",
    hint: "Gallbladder (green), porta hepatis, right & left lobes; heart model behind." },
  { id: "lm04", file: "lab2models/lab2_model_04.jpg", system: "Heart & vessels",
    answer: "Heart — anterior view",
    hint: "Anterior interventricular (LAD) & coronary vessels, right/left ventricle, auricles." },
  { id: "lm05", file: "lab2models/lab2_model_05.jpg", system: "Heart & vessels",
    answer: "Heart — base & great vessels (superior/posterior)",
    hint: "Great vessels at the base — aorta, pulmonary trunk, venae cavae, pulmonary veins." },
  { id: "lm06", file: "lab2models/lab2_model_06.jpg", system: "Heart & vessels",
    answer: "Heart — posterior view",
    hint: "Posterior surface — coronary sinus, posterior interventricular groove, atria." },
  { id: "lm07", file: "lab2models/lab2_model_07.jpg", system: "Torso / viscera",
    answer: "Torso — deep anterior (thoracic & abdominal cavity)",
    hint: "Lungs reflected, mediastinum, diaphragm, abdominal organs; muscular body wall." },
  { id: "lm08", file: "lab2models/lab2_model_08.jpg", system: "Urinary",
    answer: "Posterior abdominal wall — kidneys, suprarenal glands, great vessels",
    hint: "Kidneys (brown), suprarenal/adrenal glands (orange, on top), abdominal aorta (red) & IVC (blue)." },
  { id: "lm09", file: "lab2models/lab2_model_09.jpg", system: "Spinal cord",
    answer: "Cervical vertebra & spinal cord — cross-section",
    hint: "Vertebral body, spinal cord in cross-section (grey matter 'butterfly'), spinal nerves, vertebral vessels." },
  { id: "lm10", file: "lab2models/lab2_model_10.jpg", system: "Brain",
    answer: "Head & neck — midsagittal section",
    hint: "Cerebrum, corpus callosum, cerebellum, brainstem, nasal cavity & pharynx, spinal cord." },
  { id: "lm11", file: "lab2models/lab2_model_11.jpg", system: "Special senses (ear)", verify: true,
    answer: "Transparent cast — UNCONFIRMED (likely auditory ossicles / ear model; possibly a ventricular cast)",
    hint: "Clear amber cast on a wire stand. I'm not certain — a ChatGPT audit read it as an auditory-ossicle model, not brain ventricles. CONFIRM against your lab key before trusting this one." },
  { id: "lm12", file: "lab2models/lab2_model_12.jpg", system: "Special senses (ear)", verify: true,
    answer: "Same transparent cast — second view — UNCONFIRMED (auditory ossicles vs ventricular cast)",
    hint: "Same clear cast, different angle. Identity unconfirmed — check the lab key." },
  { id: "lm13", file: "lab2models/lab2_model_13.jpg", system: "Brain",
    answer: "Brain — midsagittal hemisphere (+ spinal-cord level cross-sections)",
    hint: "Corpus callosum, thalamus, midbrain/pons/medulla, cerebellum; inset box shows spinal cord at 4 levels." },
  { id: "lm14", file: "lab2models/lab2_model_14.jpg", system: "Spinal cord",
    answer: "Spinal cord — 3D model with cross-sectional levels",
    hint: "Spinal cord segment, dorsal/ventral roots & rootlets, meninges; inset cross-sections (cervical→sacral)." },
  { id: "lm15", file: "lab2models/lab2_model_15.jpg", system: "Brain",
    answer: "Cranial cavity — midsagittal (meninges & diencephalon)",
    hint: "Falx cerebri / dural folds, lateral ventricle, thalamus & hypothalamus, brainstem." },
  { id: "lm16", file: "lab2models/lab2_model_16.jpg", system: "Brain",
    answer: "Brain — inferior (basal) view",
    hint: "Cranial nerves, cerebral arterial circle (circle of Willis, red), brainstem, temporal/occipital lobes." },
  { id: "lm17", file: "lab2models/lab2_model_17.jpg", system: "Brain",
    answer: "Brain — superior view",
    hint: "Cerebral hemispheres, longitudinal fissure, gyri & sulci, superficial arteries." },
  { id: "lm18", file: "lab2models/lab2_model_18.jpg", system: "Heart & vessels",
    answer: "Circulatory system — whole body (arteries & veins)",
    hint: "Systemic arteries (red) & veins (blue) head→toe, heart, major organs for reference." },
];
if (typeof module !== "undefined" && module.exports) module.exports = LAB2_MODELS;
